# name: node_js

on:
  push:
    branches:  [master]
  pull_request:
    branches:  [master]

# env:
#    notification :
#                email: false

  
jobs :
  build :
    name : mybuilddemo
    runs-on: Ubuntu 18.04 LTS
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js node
        uses: actions/setup-node@v2
        with:
          node-version : '16.6.1'

      - name: "Build Docs"
        if: ${{ github.event_name == 'push' && 'pull_request'&& github.ref == 'refs/heads/master'}}
        run : |
             sudo ./.travis/affects.sh docs/ .travis || exit 0
             sudo cd docs/
             sudo source .travis/before_install.sh
             sudo npm ci
             sudo source .travis/script.sh


